### ISSUE TITLE
http://api.soundcloud.com/resolve just stopped working

### ISSUE THREAD

**Issue by mcfly10** [soundcloud/api#104]
## Title: http://api.soundcloud.com/resolve just stopped working
Issue found of: August 10th, 2021

### Endpoint(s):
* `GET /resolve`

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Fmartinwilkinson%2Ftropical-summer-nights&client_id=XXX'
```

### Expected behaviour:
Some link to use with API as it was before

### Actual behaviour:
TypeError: NetworkError when attempting to fetch resource.

This error is even in the documentation demo `https://developers.soundcloud.com/docs/api/explorer/open-api#/miscellaneous/get_resolve`

**Comment by rahul-sc** [comment]
The request is missing the OAuth header

See here for context, please
https://developers.soundcloud.com/blog/security-updates-api

**Comment by amondalbmj** [comment]
Hi @rahul-sc ,

Thanks for the info but i don't understand that from where we can get the Access token and how can we pass it with 'resolve' endpoint. 
Please share some details, it would be helpful.

**Comment by dasha-kobzeva** [comment]
Hi @amondalbmj,

Per the change mentioned in the blog post you are getting an error on /resolve endpoint because you are not authenticated.

You send a request to /resolve, providing client_id. When the resolution happens, you get a 302 response with the next URL to call, for instance, /users/some_id. That second call was stripped down from client_id, so our API treats it as unauthenticated.

To avoid such behavior your call to /resolve must contain an Authorization header so that the redirect can also pick it up and give you a proper response back.
You do not have to go through /connect to acquire a token for these calls. You can use client_credentials flow.

What it means is a call like the following:

$ curl -X POST "https://api.soundcloud.com/oauth2/token"
-H "accept: application/json; charset=utf-8"
-H "Content-Type: application/x-www-form-urlencoded"
--data-urlencode "grant_type=client_credentials"
--data-urlencode "client_id=YOUR_CLIENT_ID"
--data-urlencode "client_secret=YOUR_CLIENT_SECRET"

This returns a token, that you place in a header "Authorization: OAuth TOKEN" and send with each request.
Client_id in a query must be removed as it is not a valid way to authenticate anymore and will cause the problem.

Be aware that the token expires every hour. When that happens you can either get a new one again or use a refresh_token flow.
Soundcloud support 2 authorization flows (depending on your use case), you can find more in our guide: https://developers.soundcloud.com/docs/api/guide#authentication

Let me know if that answers your question.

**Comment by dasha-kobzeva** [comment]
you can always try it out in our API Explorer:
https://developers.soundcloud.com/docs/api/explorer/open-api#/miscellaneous/get_resolve

P.S. Do not forget to authenticate

<img width="1417" alt="Screenshot 2021-08-16 at 13 23 35" src="https://user-images.githubusercontent.com/56645782/129556301-8b4989bb-908e-4bf3-a997-64c300ff537a.png">

**Comment by mcfly10** [comment]
Everybody thanks a lot. Really it was my mistake. I did not track SC changes. Fixed everything.
