### ISSUE TITLE
API error 401

### ISSUE THREAD

**Issue by amondalbmj** [soundcloud/api#107]
Hi,

I was using the SoundCloud API with the combination of URL and client ID to get the data in JSON format but suddenly it has stopped working and I am not able to understand how I have to modify the process so that I get the data again. Currently, I face the 401 error while trying to fetch data. I am using WordPress wp_remote_get() to retrieve data and using the 'resolve' endpoint.
It would be helpful if you can suggest a sample code.

Thanks

**Comment by dasha-kobzeva** [comment]
Hi @amondalbmj,
We have recently introduced security changes that you can find here: https://developers.soundcloud.com/blog/security-updates-api
(I would highly recommend subscribing to the blog to be up-to-date with API announcements)

Per this change you are getting an error on `/resolve` endpoint because you are not authenticated.

You send a request to /resolve, providing client_id. When the resolution happens, you get a 302 response with the next URL to call, for instance, /users/some_id. That second call was stripped down from client_id, so our API treats it as unauthenticated.

To avoid such behavior your call to /resolve must contain an Authorization header so that the redirect can also pick it up and give you a proper response back.
You do not have to go through /connect to acquire a token for these calls. You can use client_credentials flow.

What it means is a call like the following:

$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=client_credentials" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET"

This returns a token, that you place in a header "Authorization: OAuth TOKEN" and send with **each** request.
Client_id in a query must be removed as it is not a valid way to authenticate anymore and will cause the problem.

Be aware that the token expires every hour. When that happens you can either get a new one again or use a refresh_token flow. 
Soundcloud support 2 authorization flows (depending on your use case), you can find more in our guide: https://developers.soundcloud.com/docs/api/guide#authentication

Let me know if that answers your question.

**Comment by amondalbmj** [comment]
Hi @dasha-kobzeva ,

Thanks for the information.
What i understand is that to access the data authentication is required.
Does that mean if a user comes to my website then he/she needs to login to listen to the tracks? 
Please let me know

Regards
Arup

**Comment by dasha-kobzeva** [comment]
> Hi @dasha-kobzeva ,
> 
> Thanks for the information.
> What i understand is that to access the data authentication is required.
> Does that mean if a user comes to my website then he/she needs to login to listen to the tracks?
> Please let me know
> 
> Regards
> Arup

Not necessarily. If your website provides only the playback, we do not require an authenticated user. 
But we do require an authenticated application. So your application should be authenticated with Soundcloud.

Look at the screenshot below. Your case is `client_credentials` flow.

<img width="666" alt="Screenshot 2021-08-16 at 14 40 30" src="https://user-images.githubusercontent.com/56645782/129565300-6d7aa96d-2eca-4be4-9940-4bbb51366b3c.png">

Please read https://developers.soundcloud.com/docs/api/guide#authentication thoroughly.

**Comment by dasha-kobzeva** [comment]
> Hi @dasha-kobzeva,
> 
> I am a bit confused here to understand the flow.
> It would be helpful if you can share a more detailed document that can have examples
> A PHP integration example. At my end, I have client_id, client_secret, and the 'sets' URL.
> 
> Regards
> Arup

Unfortunately, we cannot provide you with a PHP example. In general, cUrl can be easily applied to PHP, there are a lot of resources online.

For instance check this out: https://auth0.com/docs/flows/call-your-api-using-the-client-credentials-flow (they have an example for PHP)
This is pretty much what we expect. Afterwards, when the token is acquired, it should be added to your `'resolve` call as a header.
`-H 'Authorization: OAuth token'`

**Comment by amondalbmj** [comment]
Thanks @dasha-kobzeva , i am able to authorize the API call now but when i try to get tracks from the URL it is giving me an error in the <body> as '**We can’t find that page. A report has been sent to our tech team, and they’re looking into the problem. Please check back in a bit.**'.

**Comment by aproni34f** [comment]
> Thanks @dasha-kobzeva , i am able to authorize the API call now but when i try to get tracks from the URL it is giving me an error in the as '**We can’t find that page. A report has been sent to our tech team, and they’re looking into the problem. Please check back in a bit.**'.

Hi amondalbmj! Can you share privately your code? I am trying to achieve the same thing. Thanks

**Comment by amondalbmj** [comment]
Hi @dasha-kobzeva,

I am sharing a chunk of my code here to give you an idea of what I am trying to do. I working with WordPress at the moment.

$url_prof='https://soundcloud.com/bmjpodcasts/sets/jnnp';
        $args = array(
            'headers'     => array(
                'Authorization' => 'Bearer '.TOKEN,
            ),);
        $response = wp_remote_get( $url_prof, $args );
         echo $track = json_decode( $response['body'] );


Regards

**Comment by endquote** [comment]
@dasha-kobzeva I follow the blog and noted the API changes, but the post didn't say when they would be enforced. Is there a date on that?

I found that I could get my calls to `/resolve` working again just by moving my auth token to the header as described, but I haven't had to update all of my token management code yet. I assume my existing tokens will just expire at some point and I'll have to do further updates?

**Comment by amondalbmj** [comment]
Hi @dasha-kobzeva ,

It would be helpful if i can get an update.

**Comment by joepdooper** [comment]
Hello!

I have registered an app a while ago in the backend of SoundCloud. 

As an example I registered it for _domain-ONE.com_ and used the given client ID for this app on this domain.

Eventhough the registered app was for _domain-ONE.com_ I moved all the code to _domain-TWO.com_. For a while there were no problems; the app functioned on a different domain with the given client ID… until this month's update.

Because I can't register a new app I would like to change the domain in the backend of SoundCloud… but I can not.

Is there a chance that I can change the domain? On the _domain-ONE.com_ there is no API call anyway…

I hope so… because I have put a lot of time and effort in it and it woukd be too bad if I can not use the code.

**Comment by Subfader** [comment]
How can I use AUTH in a userscript?

**Comment by dasha-kobzeva** [comment]
> Hi @dasha-kobzeva,
> 
> I am sharing a chunk of my code here to give you an idea of what I am trying to do. I working with WordPress at the moment.
> 
> $url_prof='https://soundcloud.com/bmjpodcasts/sets/jnnp';
> $args = array(
> 'headers' => array(
> 'Authorization' => 'Bearer '.TOKEN,
> ),);
> $response = wp_remote_get( $url_prof, $args );
> echo $track = json_decode( $response['body'] );
> 
> Regards

Hi,
please check our documentation once again. You are providing a Bearer token. We accept OAuth token.

https://developers.soundcloud.com/docs/api/guide#authentication

Please also be aware, that we are not providing support for WordPress, and cannot assist you in the matter of your specific implementation.

**Comment by dasha-kobzeva** [comment]
> @dasha-kobzeva I follow the blog and noted the API changes, but the post didn't say when they would be enforced. Is there a date on that?
> 
> I found that I could get my calls to `/resolve` working again just by moving my auth token to the header as described, but I haven't had to update all of my token management code yet. I assume my existing tokens will just expire at some point and I'll have to do further updates?

Hi,

the changes will be fully rolled out by the end of September. Regarding the previous tokens, we do not have a defined solution of what will happen to them at this time. I suggest migrating to using new auth flows and being able to refresh token automatically.

**Comment by dasha-kobzeva** [comment]
> Hello!
> 
> **First of all, thank you for the API, it is great!**
> 
> I have registered an app a while ago in the backend of SoundCloud. I registered it for, as an example, for _domain-ONE.com_ and used the given client ID for this app on this domain.
> 
> Eventhough the registered app was for _domain-ONE.com_ I moved all the code to _domain-TWO.com_. For a while there were no problems; the app functioned on a different domain with the given client ID… until this month's update.
> 
> Because I can't register a new app I would like to change the domain, _domain-ONE.com_ to _domain-TWO.com_, in the backend of SoundCloud… but I can not.
> 
> Is there a chance that I can change the domain? On the _domain-ONE.com_ there is no API call anyway…
> 
> I hope so… because I have put a lot of time and effort in it and it woukd be too bad if I can not use the code.

Hi,

I'm not sure I understand what you mean by domain in this case? 

If you are referring to the redirect_uri, please check our README regarding the matter: https://github.com/soundcloud/api#how-can-i-update-my-apps-redirect_uri

P.S. we would highly appreciate if you create a separate ticket next time for your concern ;)

**Comment by joepdooper** [comment]
> P.S. we would highly appreciate if you create a separate ticket next time for your concern ;)
I replied here because I also got this error… I thought may be the solutions for others lies in the problem I have.

> I'm not sure I understand what you mean by domain in this case?
If at SoundCloud.com you registered an app you'll find these at https://soundcloud.com/you/apps. For each app there are four vars:

1. Website of your app >> I would like to change this one, because this domain is no longer in use
2. Redirect uri >> mine is empty
3. Client-id
4. Clientsecret

**Comment by dasha-kobzeva** [comment]
@joepdooper,

I see, thank you for clarifying.
So actually the website URL is an optional value, and I think this is not the root of your issue. An empty redirect URI is the required parameter for you to be able to properly authenticate. So that has to be set.

So once again, our community support can help you with setting up the redirect URI for auth and updating the website URL
https://github.com/soundcloud/api#how-can-i-update-my-apps-redirect_uri

**Comment by joepdooper** [comment]
Hi there!

> An empty redirect URI is the required parameter for you to be able to properly authenticate. So that has to be set.

So with help from the community support I have a redirect URI set in https://soundcloud.com/you/apps like this:

- Website of your app >> Wrong one (should be a different one, but shouldn't be a problem?)
- Redirect uri >> newly set to an url like so `example.com/`
- Client-id
- Clientsecret

I have a similar javascript as the docs:

```javascript
<script src="https://connect.soundcloud.com/sdk/sdk-3.3.2.js"></script>
<script>
  SC.initialize({
    client_id: 'YOUR_CLIENT_ID',
    redirect_uri: 'https://example.com/'
  });
SC.resolve(PLAYLIST_URL).then(function(playlist){
  for(var i=0;i<playlist.tracks.length;i++) {
    urlList.push(playlist.tracks[i].stream_url + '?client_id=' + CLIENT_ID);
    nameList.push(playlist.tracks[i].title);
    durationList.push(playlist.tracks[i].duration);
    lrcList.push(playlist.tracks[i].title.replace(/\s+/g, '-').toLowerCase() + '.lrc');
  }
  selectSound.appendChild(createPlaylist(nameList));
}).catch(function(error){
  console.log(error);
});
</script>
```

Which used to work, but now I get an object in the console:

```
Object { message: "A request must contain the Authorization header. For details please refer to https://developers.soundcloud.com/blog/security-updates-api.", status: 401 }
​
message: "A request must contain the Authorization header. For details please refer to https://developers.soundcloud.com/blog/security-updates-api."
​
status: 401
```

Tried different stuff but it won't work…
I am lost here. Could anybody point me in the right direction?

**Comment by dasha-kobzeva** [comment]
@joepdooper,

the support for JS SDK is deprecated. I believe there was a new version 3.3.5 from a community that addressed the header issue, so maybe try it out.

Otherwise, I would not rely on JS SDK any longer and call API directly. 
Useful links:
https://developers.soundcloud.com/docs/api/guide#authentication
https://developers.soundcloud.com/blog/security-updates-api
