### ISSUE TITLE
Error 429 (Too Many Requests)

### ISSUE THREAD

**Issue by wjumelleUS** [soundcloud/api#131]
## Title: Error 429 (Too Many Requests) on the first request of the day
Issue found of: September 10th, 2021 - since the release from 2021-09-07

### Endpoint(s):
* `​POST /oauth2​/token`

### Scope(s):
* Using SoundCloud on a TYPO3 instance. Contributors give basic SoundCloud URL (like https://soundcloud.com/USERNAME/TRACKNAME). JS resolve URL and get stream_url after firstly getting auth_token. 
Working on a preproduction environment. 

### Steps to reproduce:
``` JavaScript
var CLIENT_ID = 'MY_CLIENT_ID';
var CLIENT_SECRET = 'MY_CLIENT_SECRET';
var GRANT_TYPE = 'client_credentials';
var AuthTokenInit = false;
var AUTH_TOKEN;

if(!AuthTokenInit) {
    $.ajax({
        method: 'POST', 
        url: 'https://api.soundcloud.com/oauth2/token',
        data: {
            'grant_type' : GRANT_TYPE,
            'client_id' : CLIENT_ID,
            'client_secret': CLIENT_SECRET
        }
    })
    .done(function(data){
        AUTH_TOKEN = data.access_token; //data.access_token
        AuthTokenInit = true;
        console.log("AuthToken OK", AUTH_TOKEN);

        $.ajax({
            type: "GET",
            url: "https://api.soundcloud.com/resolve?url=" + url + '&client_id=' + CLIENT_ID,
            async: false,
            headers: {
                'Authorization': 'OAuth ' + AUTH_TOKEN
            }
        })
        .done(function(data){
            var stream_url = data.stream_url;
            //Catching the streaming url for using it with personnal player
        })
        .fail(function(jqxhr, txt, error){
            //Print Error Msg on resolving URL
        });
    })
    .fail(function(jqxhr, txt, error){
        //Print Error Msg on getting auth token
    });
}
```

### Expected behaviour:
Catching auth_token and using it for resolving url and getting stream_url for accessible player. 
Actually, i reach the limit every morning since the release and i totally can't try to move to and other way of coding.

### Actual behaviour:
429 (Too Many Requests)

**Comment by dasha-kobzeva** [comment]
Hello @wjumelleUS,
per our release notes, we have introduced the rate-limiting for client_creds flow.  (https://github.com/soundcloud/api/releases/tag/2021-09-07)

Requesting a new token on each call to `/resolve` is incorrect. 
Each token lives for an hour, and should be updated only when it expires. For updating a token you can use `refresh_token` flow. (https://developers.soundcloud.com/docs/api/guide#refreshing-tokens)

We would recommend setting the automatic process for that. In the response for token, you can see 2 params: `expires_in` and `refresh_token`. When the time is reached, you can make a call with a refresh_token and get a new token.

You can also continue using cient_creds flow, but be aware you can have only 50 tokens in 12h window. So you might hit the rate-limit again.

**Comment by JackBrit** [comment]
Hi @dasha-kobzeva  
I have a question around how the refresh flow should work. I understand how we can check if the token has expired within a single user session. 

However if my site/an app has more than 50 users open it within 12 hours would the rate limit still not be hit as they are starting 50+ sessions all needing tokens?

**Comment by dasha-kobzeva** [comment]
> Hi @dasha-kobzeva
> I have a question around how the refresh flow should work. I understand how we can check if the token has expired within a single user session.
> 
> However if my site/an app has more than 50 users open it within 12 hours would the rate limit still not be hit as they are starting 50+ sessions all needing tokens?

Do you fetch a new token for each user? If you are using client_credentials flow you don't need a token per user, as this token is not associated with a user session. So you can have centralized token management and use 1 token for all the users who access your website.

The difference between client_credentials flow and authorization_code flow is that the first one authenticates the application, and the second one: application + user.

If you are accessing only public resources one token for your application is enough. No need to create a new one for each user, especially as they are not connected to those users.

**Comment by dasha-kobzeva** [comment]
I would recommend reading a bit about authorization in general as it might help you understand the difference and use cases :)
https://oauth.net/2/

**Comment by wilsonpage** [comment]
I'm running into this issue now too. I'm caching the access token in memory for the given `expires_in` time, but I'm still maxing out the tiny rate limit of 30 per hour. I think this is because I'm running my serverside app using lambda/serverless and therefore when we hit spikes new app instances are created and the token must be requested again. Then after the spike surplus instances are destroyed and the cycle continues until my 30 calls are used up.

I understand it could be possible to workaround this by storing the token centrally in a database and have each app instance request it but this is a non-trivial engineering task and will add latency to my API calls.

Having a more lenient rate-limit on this endpoint would be helpful, even 100/hour might avoid me hitting this.

**Comment by alexweinstein** [comment]
+1 for increasing the rate limit. As I'm updating my app to enable the new authentication flow, I'm exceeding the limit very quickly.

**Comment by wjumelleUS** [comment]
Hi @dasha-kobzeva, thanks for your answer, I was new on this kind of subject and tried to make it functionnal only with JS. 
I updated my code to make calls with CURL and store token in a database. Since this update it works like a charm.
I'll be monitoring errors over the next few days. Again thanks 👍 

When you store your tokens in database, you have a token available for 1 hour. So the limit for 50 tokens / 12h seems to be clearly ok with `client_credentials` grant.

One last question, is why "expires_in" in seconds instead of providing a timestamp ? I guess it's to avoid differences in servers time zones settings ?

Have a nice day

**Comment by dasha-kobzeva** [comment]
Hi @wjumelleUS,

Great to hear it's working for you!

> One last question, is why "expires_in" in seconds instead of providing a timestamp ? I guess it's to avoid differences in servers time zones settings ?

This is actually done according to the oauth2.0 spec: https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2
(worth scrolling through it :))

**Comment by wilsonpage** [comment]
@dasha-kobzeva any chance you can bump the rate-limit enough to make in memory token caches serverless friendly?

**Comment by mgoodfellow** [comment]
Hey @wilsonpage just a thought:

You could consider just using the object/blob store of your cloud of choice - so if its AWS (I guess it is as you mention lambda?) you can use S3. From a cost perspective it is negligible. 

When a serverless spins up - it tries to pull the token information from S3 and cache it in memory. You could store the response you got back from the SC API as that raw JSON to make life easy when reading/writing.

If the token information doesn't exist in S3 - it generates a token via the SC API and stores it there. Obviously there will be start-up race conditions where you generate more tokens than you needed (last one to store will overwrite the others), but you should be well within limits.

You could go even further and have another serverless function that runs every... 45 mins (for example), which generates the token information if it isn't there. Otherwise if it is, consumes the refresh token in the payload, refreshes the token via the refresh flow, and pushes back the updated payload (new `access_token`, `expires_in` and a `refresh_token` for the next time it runs). Your existing serverless programs would simply fetch a fresh value from object storage if their in-memory one was not present or had almost expired. This separates your concerns a little more.

Obviously not as fast as redis etc. but fetching from S3 should be just as fast, if not faster than you making the request for a token from the SC API.

Anyway, just thinking out loud - maybe it is of some value to you! :)

**Comment by mgoodfellow** [comment]
Actually, as writing that I just realised you would have to convert `expires_in` to an actual time (probably UTC) when storing to object storage:

```
{
  "access_token": <>,
   "expires_at": "2021-09-20T18:25:43.511Z",
   "refresh_token": <>
}
```

When reading this back, you would then know if the token was valid or not before trying to consume it.

**Comment by wilsonpage** [comment]
Thanks for the detailed suggestion Mike.

I understand workarounds are possible, it's just a lot of hoops to ask a
developer to jump through to make a simple Search API request to Soundcloud.

**Comment by mgoodfellow** [comment]
No, indeed. You just got me thinking because you mentioned serverless, and wanting to minimize engineering (and cost!) impact. The issue I see with rate limits being simply being lifted is that your workloads could change unexpectedly (locking you out again during peak traffic time), or they might feel the need to adjust them back down in future and it becomes one more thing you need to keep an eye on.

Anyway, was just an interesting thought experiment to think of a least impact solution to your use case :)
