### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by jvaz11** [soundcloud/api#134]
Hi there, is there any news on when new developers will be able to create apps?

I've been following the same Google Forms link for a couple years, only to be met with the same message saying it's closed. I'm hoping to start working on some ideas that I have, and I'm sure I'm not alone.

**Comment by dasha-kobzeva** [comment]
Hello @jvaz11,

I cannot provide you with any estimate at this point. We know that it's a hot topic, and a lot of users would like to create their new apps, which we are excited about. 

But at the moment we must first stabilize the API so that new traffic wont affect the platform. 
Whenever we are ready to open the registration we will make an announcement.
