### ISSUE TITLE
Detect duration in the web app?

### ISSUE THREAD

**Issue by Subfader** [soundcloud/api#137]
I used to have a userscript where you could remove short tracks on /stream.

Since the players carry zero API information and the duration is unaccessable in a canvas I had to call the track API for each song. This worked fine previously.

With the new crippled API there is OAuth and a rate limit of 15K and this is no more possible for multiple users.

How can I detect track duration on the web app (soundcloud.com)?

**Comment by Subfader** [comment]
I could tell each user to register for an APi key, but you don't even allow registration! Dafuk

**Comment by dasha-kobzeva** [comment]
Hello @Subfader,

do you have an already registered app? If so, calling the API should still be quite easy as long as you have a token. You might need to have a server component for that if you don't have it already.

I would advise against calling soundcloud.com as it is not meant for this use case (quite frankly that would be abuse).

Could elaborate more on what your application is doing, your client_id so we can see if we can assist you with your needs.

Thank you

**Comment by mgoodfellow** [comment]
> With the new crippled API there is OAuth and a rate limit of 15K and this is no more possible for multiple users.

Where are you getting this? Here? https://developers.soundcloud.com/docs/api/rate-limits#:~:text=Effective%20July%201%2C%20all%20requests,%2Ftracks%2F%3Aid%2Fstream%20.

This only affects one particular endpoint - the `/stream` endpoint (and has always been this way as long as I can remember)

> Effective July 1, all requests that result in access to a playable stream are subject to a limit of 15,000 requests per any 24-hour time window. Currently, this is inclusive of all requests that are made to /tracks/:id/stream.

The API always had OAuth, however the recent change is that OAuth is now required for server-to-server communication as well (instead of just identifying with a client_id).
