### ISSUE TITLE
 Cannot see seek position on flyouts

### ISSUE THREAD

**Issue by aetinx** [soundcloud/api#175]
## Cannot see seek position on flyouts
Issue found of 6 January 2022

Issue on the website, but it's probably an issue with the API.

### Steps to reproduce:
Press VolumeUp or VolumnDown key on Windows.

### Expected behaviour:
Display the position of the song seek.

### Actual behaviour:
Doesn't display the seek, only displays 0:00 - 0:00

<img width="292" alt="image" src="https://user-images.githubusercontent.com/65425469/148399947-2b18d8a4-699c-45a7-8117-3e87591d9228.png">

**Comment by dasha-kobzeva** [comment]
Hello @aetinx,
Is it correct that you are facing the issue when using soundcloud.com and not an integration?

**Comment by aetinx** [comment]
> Hello @aetinx, Is it correct that you are facing the issue when using soundcloud.com and not an integration?

@dasha-kobzeva Correct

**Comment by dasha-kobzeva** [comment]
We will look into the issue and get back to you asap.

**Comment by dasha-kobzeva** [comment]
Hello @aetinx,

After an investigation, we have found out that the issue persists in the ModernFlyouts library we use to show the player, and was reported already in their repo: 
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/392

It seems the fix was created but is not yet released. As soon as a new version is available we will update our service.
https://github.com/ModernFlyouts-Community/ModernFlyouts/releases/tag/v0.10.0-beta.1

I will close this issue for now as no active work can be done at the moment.
