### ISSUE TITLE
[Question]: When will registration open again?

### ISSUE THREAD

**Issue by standardloop** [soundcloud/api#219]
When will registration open again?

_SoundCloud Application Registration
Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient._

Any long term update on this?

Thanks in advance.

**Comment by yanniboi** [comment]
1 month later still no response. A simple 'we're working on it' or 'we dont know yet' would be nice.

Could you at least open registrations for paying customers? Some people have work to do :(

**Comment by obrhoff** [comment]
After the latest layoffs I'm not even sure someone is responsibly for this topic.

**Comment by mikefisher84** [comment]
I tried to register in 2018 and it was closed then and don't think it ever reopened. It's such a shame because they have so much special music data that could be used in interesting ways and revitalize the platform 😔

**Comment by jimapl** [comment]
Bump!
Anyone here from SC who can give an eta?

**Comment by hanchchch** [comment]
Hi, I'm also waiting for this amazing api to be re-opened. Just wanna remind you that there's people who are still waiting :) ...

**Comment by WeeHorse** [comment]
Lucky I caught this. I was going to build a service on a number of pro accounts for stream-uploading gigs from local live venues, so that people could connect better to the live acts. Also, there is a local band here that record their music continuously, much like Can did, where Soundcloud would be a perfect pre-editing notes solution. Now I know that neither of these projects can happen using Soundcloud.

**Comment by minseo0214** [comment]
I want to use Soundcloud's API too. Any plans to re-open an API key?

**Comment by rn4n** [comment]
I was waiting for some response from soundcloud devs since 2018. IDK exactly what you would like to do but, I've following with another approach instead waiting - maybe it could help:

If you really need to use the API: on your navigator console, open the network tab and then navigate to any song on soundcloud. You could get the `client_id` from there. The bad thing about it is that the `client_id` could change at any moment, and, you cannot call all endpoints available on their open API page, there's some of then that require another authentication flow.

Other thing that I've done is web scrapping the content from some pages to collect the data I want.

Both are ugly solutions but, at least it's functional for while. 😃 

I would like to understand what's been "blocking" the registration of new applications for 5 years, but since they don't communicate effectively with the community or give an answer about the API, I preferred to migrate and work with content from other platforms. Sad.

**Comment by WeeHorse** [comment]
Thank you @rn4n. Yes, it is sad. Makes me wonder to what extent SoundCloud is an active entity, or just a passive holding org.

**Comment by yanniboi** [comment]
Yea with regard to scraping, soundcloud has a script tag in the dom on sound pages that starts with `window.__sc_hydration = `:

![image](https://user-images.githubusercontent.com/1744957/223663814-c09bf7ea-a1e1-405e-b2d5-560f12d7c8f2.png)

You can scrape that and parse the json to get some pretty detailed data dumps:

![image](https://user-images.githubusercontent.com/1744957/223664071-e7de9b08-ca08-4cee-8675-8f84de8b330b.png)


![image](https://user-images.githubusercontent.com/1744957/223664095-99d9f486-12b3-4aaf-8b6a-dbe0210fed79.png)


Its slightly better than scaping the dom for specific markup structure which is more likely to change. Has been working for me for a year now.

I get most of my information from rss feeds, the one thing I need from sc that I cant get from the feed is the tags for a certain sound, so I use the dom scraping to get the tags.

**Comment by chikiuso** [comment]
I also would like to apply for app for the token access to use the api , I will upgrade my plan once I got the api, thanks

**Comment by mekkanix** [comment]
October 14h, 2023 and still no response nor updates on their message... A bit of serious and news about this would be nice, especially for (long-term) paying users.

**Comment by MariaVWSoundCloud** [comment]
Hey everyone, just to make sure everyone sees this: https://github.com/soundcloud/api/issues/246 - the answer is there... ;)
