### ISSUE TITLE
OAuth 2.1: Invalid grant

### ISSUE THREAD

**Issue by ahbou** [soundcloud/api#322]
## Title: authorization_code grant returns invalid grant
Issue found of: September 20th, 2020

### Endpoint(s):
* `POST https://secure.soundcloud.com/oauth/token`

### Scope(s):
* authorization_code

### Steps to reproduce:
```bash
curl --location 'https://secure.soundcloud.com/oauth/token' \
--header 'Accept: application/json; charset=utf-8"' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id=XXXXXXX' \
--data-urlencode 'client_secret=XXXXXXX' \
--data-urlencode 'code=XXXXXXXXX' \
--data-urlencode 'code_verifier=m8WrZP9VeSxQu2TlQnyLdFrtbx74MSxEVdL0xDw-Uk0' \
--data-urlencode 'redirect_uri=http://localhost:8080/soundcloud-auth'
```

### Expected behaviour:
Return an access token 

### Actual behaviour:
400 Bad Request

```
{
    "error": "invalid_grant"
}

**Comment by youssefhassan** [comment]
This sounds like an issue with the code verifier and code challenge, can you share how they are generated?
This is a working generator https://example-app.com/pkce
Please keep this in mind in the PKCE generator website when clicking on Generate Random String it doesn't update base64 field, so you need to click on Calculate Hash one more time

**Comment by superturboryan** [comment]
Hi @youssefhassan , is there an Open API specification page for the endpoints that have been migrated to `https://secure.soundcloud.com/` ? 

I see the [API guide](https://developers.soundcloud.com/docs/api/guide#authentication) has been updated to show we should use `secure.soundcloud.com/authorize` and `secure.soundcloud.com/oauth/token` instead of the deprecated `api.soundcloud.com/` auth endpoints, it would be nice to have an API specification page for these new endpoints

**Comment by youssefhassan** [comment]
We are working on providing more extensive authentication guide with the new methods, were you able to make it work?

**Comment by ahbou** [comment]
I was 👍 
My issue was sending the code challenge instead of the code verifier in the token exchange request.

**Comment by superturboryan** [comment]
Yes, I've figured it out as well, thanks for replying @youssefhassan 🤝

**Comment by youssefhassan** [comment]
Issue solved
