### ISSUE TITLE
invalid_client (401 unauthorized) error coming while migrating to new client credential api

### ISSUE THREAD

**Issue by kejul-vyas-mck** [soundcloud/api#339]
## Title: Invalid_Client (401 Unauthorized) error coming from https://secure.soundcloud.com/oauth/token API
Issue found of: Oct 23th, 2024

### Endpoint(s):
* `POST https://secure.soundcloud.com/oauth/token`

### Scope(s):
application is uses client_credentials workflow for authentication

### Steps to reproduce:
```bash
curl --location 'https://secure.soundcloud.com/oauth/token' \
--header 'accept: application/json; charset=utf-8' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic Base64(client_id:client_secret)' \
--data-urlencode 'grant_type=client_credentials'
```

### Expected behaviour:
It should return access_token, refresh_token along with other parameters as per the documentation here - https://developers.soundcloud.com/docs/api/guide#client-creds

### Actual behaviour:
401 Unauthorized error

**Comment by youssefhassan** [comment]
Hey @kejul-vyas-mck, my suspicion would be around whether the Base64 is done properly, it can be confusing. 
# The Base64 encoded string of "my_client_id:my_client_secret" is "bXlfY2xpZW50X2lkOm15X2NsaWVudF9zZWNyZXQ="
Please let us know if this was the issue or otherwise we are happy to assist further.

**Comment by kejul-vyas-mck** [comment]
Thank @youssefhassan this resolved the issue to generate the access_token and refresh_token.

However, when I am calling the upload track api with the above generate access_token, I am unable to upload the audio. It gives Unauthorized 401 error.
 
<img width="469" alt="image" src="https://github.com/user-attachments/assets/2e1c03db-a270-428c-a0fd-8cf2e2a2f0fd">

Upload track api request I followed from the documentation - https://developers.soundcloud.com/docs/api/guide#uploading-files
<img width="824" alt="image" src="https://github.com/user-attachments/assets/68ce75a0-2127-4486-83cd-ef2f7922741a">

**Comment by youssefhassan** [comment]
Can you please share your soundcloud username and application name so I can debug the issue? 
thanks for reporting :)

**Comment by youssefhassan** [comment]
I deleted the message as it had the client id that can be misused, I will look into the issue soon. From the configuration, it looks that with a valid token, you should be able to make requests to the public api. Is it only giving 401 on track uploads or other endpoints as well?

**Comment by mgoodfellow** [comment]
Hi,

It seems like you are requesting a `client_credential` grant - this doesn't have a user context associated with it and it can only be used for GET operations on "public" endpoints, such as /tracks or /track/{id} etc.

In order to make mutations to user data, you need to go through the OAuth connect flow and authorize a specific user context against your app via the connect with soundcloud web flow. Then you can make requests to user context endpoints (/me) and also perform mutations, such as uploading/editing tracks/playlists etc with the OAuth token generated from this.

https://developers.soundcloud.com/docs/api/guide#authentication

You are looking for the Authorization Code Flow, not the Client Credentials Token Exchange Flow

Hope this helps!

**Comment by kejul-vyas-mck** [comment]
@mgoodfellow The Authentication workflow works now with @youssefhassan's given solution (needed to encrypt the clientid:clientsecret to base64 encoded string). 

@youssefhassan the access_token isn't working with any of the SoundCloud api. I tried checking below api to get list of tracks uploaded - 
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/7a92e4e7-044b-468e-8555-15a69c817fca">

**Comment by youssefhassan** [comment]
This shouldn't be the case, I'm thinking if the token could have been expired or the client credentials were revoked. Can you please let us know which user the app is attached to and the name of the app?

**Comment by kejul-vyas-mck** [comment]
@youssefhassan I have used unexpired tokens all the time. please find the user and app details below:
user email id - Charmaine_Rice@mckinsey.com
name of the app - https://soundcloud.com/mckinsey

**Comment by kejul-vyas-mck** [comment]
@youssefhassan following up on this issue - do we have any solution?

**Comment by youssefhassan** [comment]
Hey @kejul-vyas-mck, your application is fine, we are currently generate only expiring tokens for better security. So you'd need to generate a new token or refresh the current token as depicted in the [API Guide](https://developers.soundcloud.com/docs/api/guide#authentication) under Refreshing Tokens
