### ISSUE TITLE
Track not returned on user track collection, but can be fetched directly

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#52]
## Title: Track not returned on user track collection, but can be fetched directly
Issue found of: 21/04/2021

### Endpoint(s):
* `GET /users/{id}/tracks`
* `GET /tracks/{id}`

### Scope(s):
* Logged in user with oauth_token (`client_id`, `client_secret` & `oauth_token`)
* AND no_auth (just `client_id`)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/796759108/tracks?limit=10&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
A list of tracks matching their public profile (5 tracks on this users profile)

### Actual behaviour:
Their latest track is not showing (caching issue?) - returns 4 tracks with the latest, ID 1032252502 not returned.

However, the latest track can be fetched directly, it isn't blocked from the API:

```bash
curl --request GET \
  --url 'https://api.soundcloud.com/tracks/1032252502?client_id=DONT_SHARE_CLIENT_ID'
```

Returns 200 with the expected track

**Comment by mgoodfellow** [comment]
It appears tracks returned in the user collection have:

`"access": "playable"`

And this track when fetched individually has:

`"access": "blocked"`

This property isn't in the schema or documented: https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/get_tracks__track_id_

I would assume this is the issue, but I'm not sure what controls this setting? Is it from the user option:

![image](https://user-images.githubusercontent.com/6501186/115552228-fc3a9a00-a2a3-11eb-9659-3699952deea2.png)

Thanks for any info

**Comment by anikarni** [comment]
Hey @mgoodfellow , thanks for engaging with the issue tracker.

Indeed, fetching tracks through our Public API would always only return playable tracks (free content, available for the caller's country). However, because of popular demand we have just this week released the `access` field that would make it possible to retrieve and filter blocked tracks. We have documented the way to request blocked tracks in https://developers.soundcloud.com/docs/api/explorer/open-api#/users/get_users__user_id__tracks. Note that you will be able to see the track if you request `access=playable,preview,blocked`, but streaming of blocked tracks will not be possible.

A track can be blocked due to it being Go+ content (which is not accessible through the API) or due to geoblocking or blocked by the rightsholders themselves (by that setting you showed).

You're right that the `access` field in the Track object is not showing. Will take a look at why that is.

**Comment by mgoodfellow** [comment]
Wow, thanks @anikarni - this is a great and much needed update for the API

Apologies I hadn't noticed that new filter in the /users/{id}/tracks search.

Thank you so much for the fast response and for this awesome update to the API :)
