### ISSUE TITLE
[Question] Refresh token limited at one usage ?

### ISSUE THREAD

**Issue by Vivien60** [soundcloud/api#80]
Hello,
I'm trying to implement the new authentication flow. As I'm in urge, and the redirect_uri behind a VPN, i do some things "manually".
I manage to get a refresh_token and an access_token. 
The problem is the refresh token seems to change everytime I'm requesting a new access token ( previous is cancelled and a new is added in the request answer ). This is the curl I use, got it from https://developers.soundcloud.com/blog/security-updates-api :
curl --request POST \
--url https://api.soundcloud.com/oauth2/token \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data client_id=CLIENT_ID \
--data client_secret=CLIENT_SECRET \
--data grant_type=refresh_token \
--data refresh_token=MY_REFRESH_TOKEN
First time, I get this answer :
{"access_token":"NEW_ACCESS_TOKEN","expires_in":3599,"refresh_token":"NEW_REFRESH_TOKEN","scope":""}
Second time, I get this one :
{"code":401,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}

The request I've done to get my refresh token :
https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&response_type=code&scope=&state=[random_string]&redirect_uri=YOUR_REDIRECT_URI

curl -X POST "https://api.soundcloud.com/oauth2/token" \
 -H  "accept: application/json; charset=utf-8" \
 -H  "Content-Type: application/x-www-form-urlencoded" \
 -d "grant_type=authorization_code&client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&redirect_uri=YOUR_REDIRECT_URI&code=YOUR_CODE"
 
 Where is my error ? 
 
 Thanks !

**Comment by Vivien60** [comment]
Sorry, didn't found how to add the "Question" label

**Comment by Vivien60** [comment]
OK, I just found this ticket : https://github.com/soundcloud/api/issues/72 .
It says that the refresh token can be used only once, and that's the desired behaviour. It's not compatible with our asynchronus process :
send the job ( "publish to soundcloud this file") to a component with all the parameters ( that's totally internal : no http request, no cur, nothing... ). Problem is the component has no access to the database, so can't register new refresh token if it requests new one. I know that's our problem, but is there a chance the refresh token can be illimited ? Or with a large number of uses ?

**Comment by rahul-sc** [comment]
In the near future, yes - our teams are working on it. But for now, a new token pair is issued when you refresh it

**Comment by matthew-healy** [comment]
Hi @Vivien60!

As you noted, refresh tokens can only be used once. The reason for this is a security one. A refresh token represents proof that your application has already been authenticated (either for a specific user if you’re using the auth code grant exchange, or without a user if you’re using the client credential grant exchange). While access tokens are short-lived and multi-use, refresh tokens are longer-lived but explicitly single-use. Since your application only sends the refresh token to the server when it needs to exchange it (and notably does not include it in any other requests), and the token is immediately expired on use, the risk of a refresh token leaking & being misused is significantly lower. If we allowed refresh tokens to be used multiple times, we would lose the guarantee that it will _only_ be sent to us immediately before it is expired.

I’m sorry this currently causes architectural issues for your application, but it’s not something we would consider changing.

Regards,
Matthew
